#!/bin/sh
set -e

exec setup.d/folder-structure.sh
exec setup.d/cli-tools.sh
exec setup.d/homebrew.sh
exec setup.d/shell.sh
exec setup.d/python.sh
exec setup.d/node.sh
exec setup.d/git.sh
exec setup.d/ssh.sh
exec setup.d/misc.sh
